apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smtp4dev-pvc
  namespace: mp4-to-mp3 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard